spring.application.name=app_security

spring.datasource.url=jdbc:postgresql://localhost:5430/security_bank
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Password de JWT
jwt.secret=jxgEQe.XHuPq8VdbyYFNkAN.dudQ0903YUn4
jwt.expiration=60

# Configuración de Hibernate / JPA
# 'update' crea o actualiza las tablas automáticamente según tus entidades
# create-drop, update
#spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar las consultas SQL en la consola (útil para desarrollo)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para PostgreSQL
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect